### ISSUE TITLE
RotaryCraft v10a crashing with PneumaticCraft latest on dedicated server only

### ISSUE THREAD

**Issue by spamenigma** [ReikaKalseki/Reika_Mods_Issues#483]
Getting the following crash since updating RotaryCraft/DragonAPI etc.. to v10a. Worked when I tested client side but dedicated server crashes with the following:

http://pastebin.com/CssGgkVU

extract:

Caused by: java.lang.NoSuchMethodError: net.minecraft.block.Block.func_149720_d(Lnet/minecraft/world/IBlockAccess;III)I
    at pneumaticCraft.common.fluid.Fluids$1.getColor(Fluids.java:32)
    at Reika.RotaryCraft.Auxiliary.BlockColorMapper.addFluids(BlockColorMapper.java:298)
    at Reika.RotaryCraft.Auxiliary.BlockColorMapper.<init>(BlockColorMapper.java:249)
    at Reika.RotaryCraft.Auxiliary.BlockColorMapper.<clinit>(BlockColorMapper.java:41)
    at Reika.RotaryCraft.RotaryCraft.postload(RotaryCraft.java:498)

Thanks

**Comment by ReikaKalseki** [comment]
Fixed.
