### ISSUE TITLE
[V19a] Reactorcraft crash on server load

### ISSUE THREAD

**Issue by aking4125** [ReikaKalseki/Reika_Mods_Issues#1655]
The server crashes within about a minute into loading after upgrading DragonAPI, RotaryCraft and ReactorCraft from V18b to V19a. Regardless of fresh world or not. Could be something else though. 

{Description: Exception in server tick loop

Reika.DragonAPI.Exception.RegistrationException: REACTORCRAFT has a registration error:
Failed to load REACTOR due to a missing class: java.lang.NoClassDefFoundError: Reika/ReactorCraft/TileEntities/TileEntityReactorGenerator
Contact Reika immediately!}

Maybe I have to regenerate the config files?

https://pastebin.com/QxWbbBD9

**Comment by ReikaKalseki** [comment]
#1654
