### ISSUE TITLE
Reactorcraft crash: Trying to load BlockColorInterface on server

### ISSUE THREAD

**Issue by jarrett** [ReikaKalseki/Reika_Mods_Issues#498]
This issue occurred after updating DragonAPI, RotaryCraft, ReactorCraft, and ElectriCraft to 1.7.10 V10b. ReactorCraft [tries to use](https://github.com/ReikaKalseki/ReactorCraft/blob/master/ReactorCraft.java#L394) `BlockColorInterface`, [which is client-only](https://github.com/ReikaKalseki/RotaryCraft/blob/master/API/BlockColorInterface.java#L23). This works fine in single-player. But on the server, this crashes with `Attempted to load class Reika/RotaryCraft/API/BlockColorInterface for invalid side SERVER`. Here's the full log from FML:

```
[18:30:40] [Server thread/ERROR] [FML/]: The following problems were captured during this phase
[18:30:40] [Server thread/ERROR] [FML/]: Caught exception from ReactorCraft
java.lang.NoClassDefFoundError: Reika/RotaryCraft/API/BlockColorInterface
  at Reika.ReactorCraft.ReactorCraft.postload(ReactorCraft.java:394) ~[ReactorCraft.class:?]
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_72]
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_72]
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_72]
  at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_72]
  at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[FMLModContainer.class:?]
  at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_72]
  at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_72]
  at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
  at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
  at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
  at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
  at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
  at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:?]
  at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:?]
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_72]
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_72]
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_72]
  at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_72]
  at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
  at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
  at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
  at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
  at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
  at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
  at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742) [Loader.class:?]
  at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97) [FMLServerHandler.class:?]
  at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:319) [FMLCommonHandler.class:?]
  at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210) [lt.class:?]
  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
  at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.ClassNotFoundException: Reika.RotaryCraft.API.BlockColorInterface
  at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
  at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_72]
  at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_72]
  ... 32 more
Caused by: java.lang.RuntimeException: Attempted to load class Reika/RotaryCraft/API/BlockColorInterface for invalid side SERVER
  at cpw.mods.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:50) ~[forge-1.7.10-10.13.4.1448-1.7.10-universal.jar:?]
  at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.11.jar:?]
  at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.11.jar:?]
  at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_72]
  at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_72]
  ... 32 more
```

**Comment by zemerick** [comment]
You need to redownload again, including DragonAPI. That's also not the full log. Crash log would be fine though, so don't need the entire FML log. One of the critical pieces of information missing is modlist.

**Comment by jarrett** [comment]
You folks move fast! Nice work. Thanks!
